import CoreGraphics
import Foundation

/// The Home Screen icons the user can pick in Settings → App Icon. `primary`
/// is the default meow icon; every other case must have a matching
/// `.appiconset` in Assets.xcassets and be listed in
/// `ASSETCATALOG_COMPILER_ALTERNATE_APPICON_NAMES` (project.yml).
///
/// Every case also needs a `<rawValue>Preview.imageset` — the picker renders
/// artwork, not a text list, and `.appiconset` contents are not reliably
/// loadable through `UIImage(named:)` at runtime (the primary icon in
/// particular is not exposed under its asset name). The previews are
/// downscaled copies generated by `scripts/generate-app-icon.sh`.
enum AppIcon: String, CaseIterable, Identifiable {
    /// Default meow icon (`AppIcon.appiconset`).
    case primary = "AppIcon"
    /// Flat-style cat leaping over a brick wall (`AppIconLeap.appiconset`).
    case leap = "AppIconLeap"
    /// Calico kitten peeking over an ivy-covered wall at sunset
    /// (`AppIconSunset.appiconset`).
    case sunset = "AppIconSunset"
    /// Black cat resting on a moonlit wall (`AppIconMidnight.appiconset`).
    case midnight = "AppIconMidnight"

    /// Fraction of an icon's width that iOS rounds off when it masks artwork
    /// for the Home Screen. The picker rows and the in-app status glyph both
    /// mask with this, so an icon reads as the same shape wherever it appears.
    static let squircleRadiusRatio: CGFloat = 0.22

    /// Corner-radius fraction the status glyph masks this icon's artwork with.
    ///
    /// Zero for the primary mascot: its squircle is baked into the alpha
    /// channel, and re-masking a shape that is already rounded would only
    /// shave artwork off the corners. The alternates are full-bleed Home
    /// Screen art, so the glyph has to round them itself.
    var glyphCornerRadiusRatio: CGFloat {
        self == .primary ? 0 : Self.squircleRadiusRatio
    }

    var id: String {
        rawValue
    }

    /// Argument for `UIApplication.setAlternateIconName(_:)` — `nil` selects
    /// the primary icon.
    var alternateIconName: String? {
        self == .primary ? nil : rawValue
    }

    /// Asset-catalogue name of the imageset the picker renders as a tile.
    var previewAssetName: String {
        rawValue + "Preview"
    }

    /// Localizable.strings key for the display label in the picker.
    var titleKey: String {
        switch self {
        case .primary: "settings.appIcon.primary"
        case .leap: "settings.appIcon.leap"
        case .sunset: "settings.appIcon.sunset"
        case .midnight: "settings.appIcon.midnight"
        }
    }

    /// Maps `UIApplication.alternateIconName` back to a case. Unknown names
    /// (an icon dropped in an app update) fall back to `.primary`.
    init(alternateIconName: String?) {
        self = alternateIconName.flatMap(AppIcon.init(rawValue:)) ?? .primary
    }

    /// Asset the in-app status glyph draws while this icon is installed.
    ///
    /// The primary icon ships a dedicated pair of transparent-cornered
    /// mascots — `AppMarkConnected` hangs a paw over the wall while the tunnel
    /// is up. The alternates exist only as full-bleed Home Screen art, so they
    /// reuse the picker's preview and lean on the glyph's stage dot alone to
    /// show connection state.
    func glyphAssetName(connected: Bool) -> String {
        switch self {
        case .primary: connected ? "AppMarkConnected" : "AppMark"
        case .leap, .sunset, .midnight: previewAssetName
        }
    }
}
